/***********************************************
	MPX: The MultiProgramming eXecutive
	Start Header
	
	Authors: Dakota Kirby
			 Corey Hartley
			 Thomas Blaschak
			 Wisam Al-Malack

	File Name: CONFIG.H
	
	Purpose: This file contains all information on
			version information, date modified, and
			various structures of PCB, and queues
	
	Procedures In This Program
		closing
	
***********************************************/
// Version Information
#define VER 2.0
#define DATE 9/25/2013
