/***********************************************
	MPX: The MultiProgramming eXecutive
	Start Program
	
	Authors: Dakota Kirby
			 Corey Hartley
			 Thomas Blaschak
			 Wisam Al-Malack

	File Name: ERROR.H
	
	Purpose: This file is to set-up function 
			 prototypes and declare different 
			 error codes to produce error statements
	
***********************************************/

#include "mpx_supt.h"
#include "config.h"

#define OK 0
#define PCB_DOESNT_EXIST 1
// other defines as needed 